PhpStorm recipe and shellcheck fixes

diff --git a/pm-helper b/pm-helper
--- a/pm-helper
+++ b/pm-helper
@@ -7,10 +7,11 @@ if ! [ -f "$1" ]; then
 fi
 
 cd "$BUILD_DIR"
+# shellcheck source=/dev/null
 source "$1"
 (case "$2" in
     download) download-phase ;;
        build)    build-phase ;;
      install)  install-phase ;;
            *) echo "unknown phase '$1'" && exit 2
-esac) || echo "error: phase $1 failed"
+esac) || echo "error: phase '$2' failed"
diff --git a/pm-install b/pm-install
--- a/pm-install
+++ b/pm-install
@@ -9,6 +9,17 @@ usage() {
     echo 'usage: pm-install NAME VERSION'
 }
 
+find-manifest() {
+    local name="$1"
+    local manifest
+    manifest="$(find "$PM_REPOSITORY" \
+        -type f \
+        -name "$name.sh" \
+        -print \
+        -quit 2> /dev/null)"
+    MANIFEST="$(readlink -f "$manifest")"
+}
+
 if [ "$#" -lt 2 ]; then
     usage
     exit 2
@@ -31,9 +42,8 @@ if [ -z "$NAME" ] || [ -z "$VERSION" ]; then
 fi
 export NAME VERSION
 
-MANIFEST="$PM_REPOSITORY/$NAME.sh"
-if ! [ -f "$MANIFEST" ]; then
-    echo "error: package ${NAME} not found"
+if ! find-manifest "$NAME"; then
+    echo "error: package '${NAME}' not found"
     exit 1
 fi
 export MANIFEST
